### PR TITLE
fix: use query params in requests

### LINKED ISSUE #37: Proxy not forwarding query string params
It appears that query string parameters are not forwarded to Discord. For example:
GET https://fullchannellink/messages?limit=anything turns to https://fullchannellink/messages

This happens on L239 of main.rs, where request_path uses .path on the request uri, which ditches any querystring stuff.

### PR DESCRIPTION
**Pull request by Gelbpunkt**
If there are query parameters, they need to be added to the new URI before requesting.

Fixes #37

### CODE REVIEW

File: src/main.rs [hunk 1]
```diff
@@ -270,7 +270,13 @@ async fn handle_request(
...
+    let mut uri_string = format!("https://discord.com{}{}", api_path, trimmed_path);
+    if let Some(query) = request.uri().query() {
+        uri_string.push('?');
+        uri_string.push_str(query);
+    }
+
+    let uri = match Uri::from_str(&uri_string) {
         Ok(uri) => uri,
         Err(e) => {
             error!("Failed to create URI for requesting Discord API: {:?}", e);
```
Comment (vilgotf) [inline src/main.rs:283]: This could be converted to `if let Err(e)` to match twilight's code style, but it can be fixed later

**Review by vilgotf — DISMISSED** [review]
Looks good, one small nit that you can ignore

File: src/main.rs (hunk 1 above)
Comment (spring4175) [reply src/main.rs:283]: It can't be since the Ok is pattern matched.

**Review by spring4175 — APPROVED** [review]

**Review by vilgotf — APPROVED** [review]

**Review by AEnterprise — APPROVED** [review]
